# --- データ収集ソース設定 ---
# このファイルで、各fetcherが収集する情報ソースを管理します。
# 各項目の値はカンマ(,)区切りで複数指定できます。

[YouTube]
# 収集対象のYouTubeチャンネルまたは再生リストのURL
urls = 
    https://www.youtube.com/@AC_Investor,
    https://www.youtube.com/@mabuchi-mariko

[Twitter]
# 収集対象のTwitterアカウント名
accounts = 
    elonmusk,
    VitalikButerin

[Mail]
# .envファイルで設定したIMAPサーバーに接続し、以下の条件でメールをフィルタリングします。
# 収集対象のメール送信元アドレス
from_email = mailmag@mag2premium.com
# 収集対象のメール宛先アドレス (通常は.envのEMAIL_ADDRESSと同じ)
to_email = kkobayashi12356@gmail.com
